## 1. Import library and dataset

In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns

In [2]:
df = pd.read_csv("C:/Users/ADMIN/Desktop/Ok/ML/LOL_Dataset.csv") 
df.head()

,game_id,start_utc,duration,queue,platform_id,map_id,game_mode,game_version,participant_id,champion_id,...,final_omnivamp,final_power,final_powerMax,final_spellVamp,team_baronKills,team_dragonKills,team_towerKills,team_champKills,team_riftHeraldKills,team_inhibitorKills
0,3746362208,2025-02-19T23:59:41Z,2551,Ranked Solo/Duo,EUN1,11,CLASSIC,15.3.656.4086,1,266,...,0,0,0,0,0,4,10,67,0,4
1,3746362208,2025-02-19T23:59:41Z,2551,Ranked Solo/Duo,EUN1,11,CLASSIC,15.3.656.4086,2,141,...,0,757,1260,0,0,4,10,67,0,4
2,3746362208,2025-02-19T23:59:41Z,2551,Ranked Solo/Duo,EUN1,11,CLASSIC,15.3.656.4086,3,99,...,0,699,1729,0,0,4,10,67,0,4
3,3746362208,2025-02-19T23:59:41Z,2551,Ranked Solo/Duo,EUN1,11,CLASSIC,15.3.656.4086,4,110,...,0,1210,2110,0,0,4,10,67,0,4
4,3746362208,2025-02-19T23:59:41Z,2551,Ranked Solo/Duo,EUN1,11,CLASSIC,15.3.656.4086,5,412,...,0,366,965,0,0,4,10,67,0,4

## 2. Data processing

In [15]:
import itertools

df = df[df["duration"] >= 900].copy()
teams = df.groupby(["game_id", "win"])["champion_name"].apply(list).reset_index()

def win_combos(teams, size):
    cnt = []
    for i in teams:
        cnt.extend(list(itertools.combinations(sorted(i), size)))
    return cnt

all_combos = win_combos(teams["champion_name"],2)
win_combos = win_combos(teams[teams["win"] == True]["champion_name"],2)

coms_cnt = pd.Series(all_combos).value_counts().rename("total_games")
win_coms_cnt = pd.Series(win_combos).value_counts().rename("wins")

duo_df = pd.concat([coms_cnt, win_coms_cnt], axis = 1).fillna(0)
duo_df["win_rate"] = np.where(duo_df["total_games"] > 0, duo_df["wins"]/duo_df["total_games"], 0)


top_duos = duo_df[duo_df["total_games"] >= 30].sort_values(by = ["win_rate", "total_games"], ascending = [False, False])
top_duos.head()

                      total_games  wins  win_rate
(Amumu, Jhin)                  30  24.0  0.800000
(Diana, Janna)                 40  31.0  0.775000
(Jinx, Nunu)                   44  33.0  0.750000
(Garen, Jhin)                  39  29.0  0.743590
(MonkeyKing, Twitch)           31  23.0  0.741935